### PR TITLE
replace changeset workaround w/ correct helper usage

### PR DESCRIPTION
**Pull request by briarsweetbriar**

### CODE REVIEW

**Review by bkoelman — APPROVED** [review]
Thanks, looks pretty clean now.

**Comment by bkoelman** [comment]
@briarsweetbriar When trying to create an empty todo-item, a warning gets logged in the browser console:

image

This also occurs when trying to log in with an invalid username/password combination. The warning was introduced in #13. Is this something you can fix?

Another thing I noticed is that the build prints new warnings since #13. This is the output on my system after running `git clean -xdf`:

image

Do you think these are worth fixing, or should they just be ignored? In particular, the version mismatch on webpack looks unintentional to me.

**Comment by briarsweetbriar** [comment]
@bkoelman thanks for the feedback! i've dealt w/ all the deprecations that were printing on `yarn install`, though the deprecation from submitting an empty todo item is coming from the `ember-notify` addon. i could an open a pr to fix it in their repo, but it might be awhile before we're able to pull that back into the example app

**Comment by bkoelman** [comment]
@briarsweetbriar Thanks; I'm no longer getting warnings during install/build. If time permits, it would be great if you could submit a fix to ember-notify.

**Pull request merged**
